services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=my_pwd
      - MYSQL_DATABASE= api  
    ports:
      - 3306:3306  
    networks:
      - app-networks
  api:
    image: guiengel23/checkpoint4:latest
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_DATABASE=api
      - DB_USER=root
      - DB_PASSWORD=root_pwd
    networks:
      - app-networks

networks:
  app-networks: