name: Continuous Integration

on:
  push:
    branches:
      - feature
      - hotfix
      - develop  

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v5
            -   name: Build da Aplicação
                run: mvn clean package -DskipTests
            -   name: Execução de Testes Unitários
                run: mvn test -Dtest='!GlobalsolutionApplicationTests'
